name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      MESA_SHADER_CACHE_DISABLE: 'true'
      DISPLAY: ':99.0'

    steps:
    - uses: actions/checkout@v4

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y xorg libx11-6 libxxf86vm1 libxcursor1 libxi6 \
          libxrandr2 libxinerama1 libegl1 libxkbcommon0 libdbus-1-3 pulseaudio \
          mesa-utils xvfb

    - name: Start xvfb
      run: |
        /sbin/start-stop-daemon --start --quiet \
          --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background \
          --exec /usr/bin/Xvfb -- :99 -screen 0 1280x720x24 -ac +extension GLX +extension RANDR

    - name: Install Project
      run: make install

    - name: GLX info
      run: glxinfo -B

    - name: Run Tests
      run: make test
