name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install system dependencies
      run: sudo apt-get install -y pulseaudio libegl1

    - name: Install Project
      run: make install

    - name: Generate Docs
      run: make test
