name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get upgrade
        sudo apt-get install -y xserver-xorg-video-dummy pulseaudio libegl1

    - name: Setup dummy display
      run: sudo X -config utils/dummy-1920x1080.conf &

    - name: Install Project
      run: make install

    - name: Run Tests
      run: DISPLAY=:0 make test
