name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install system dependencies
      run: sudo apt-get install -y xorg pulseaudio libegl1

    - name: Setup dummy display
      run: |
        export DISPLAY=:99
        sudo Xvfb -ac :99 -screen 0 1920x1080x24 > /dev/null 2>&1 &

    - name: Install Project
      run: make install

    - name: Run Tests
      run: make test
