name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DISPLAY: ':0'

    steps:
    - uses: actions/checkout@v4

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y xserver-xorg-video-dummy pulseaudio libegl1 mesa-utils strace

    - name: Show runners
      run: sudo cat /var/lib/act-runner/.runner

    - name: Setup dummy display
      run: sudo X -config utils/dummy-1920x1080.conf &

    - name: Install Project
      run: make install

    - name: GLX info
      run: glxinfo -B

    - name: Run Tests
      run: make test
